import React, { forwardRef } from 'react';
import { View as NativeView, ViewStyle } from 'react-native';

import { ContainerProps } from './type';

function buildStyle(props: ContainerProps): ViewStyle {
  const style: ViewStyle = {
    flex: props.flex,
    flexShrink: props.flexShrink,
    flexWrap: props.flexWrap,
    position: props.absolute ? 'absolute' : props.position,
    flexDirection: props.row ? 'row' : props.col ? 'column' : undefined,
    justifyContent: props.justify,
    alignItems: props.align,
    alignSelf: props.self,
    width: props.width ?? props.square,
    height: props.height ?? props.square,
    maxWidth: props.maxWidth,
    minWidth: props.minWidth,
    maxHeight: props.maxHeight,
    minHeight: props.minHeight,
    margin: props.m,
    marginHorizontal: props.mx,
    marginVertical: props.my,
    marginTop: props.mt,
    marginBottom: props.mb,
    marginLeft: props.ml,
    marginRight: props.mr,
    padding: props.p,
    paddingHorizontal: props.px,
    paddingVertical: props.py,
    paddingTop: props.pt,
    paddingBottom: props.pb,
    paddingLeft: props.pl,
    paddingRight: props.pr,
    gap: props.gap,
    backgroundColor: props.color,
    borderRadius: props.radius,
    borderTopLeftRadius: props.radiusTop,
    borderTopRightRadius: props.radiusTop,
    borderBottomLeftRadius: props.radiusBottom,
    borderBottomRightRadius: props.radiusBottom,
    borderWidth: props.border,
    borderColor: props.borderColor,
    overflow: props.overflow,
    opacity: props.opacity,
    top: props.top,
    bottom: props.bottom,
    left: props.left,
    right: props.right,
  };

  if (props.round !== undefined) {
    style.width = props.round;
    style.height = props.round;
    style.borderRadius = props.round / 2;
  }

  return style;
}

export const View = forwardRef<NativeView, ContainerProps>(function ContainerComponent(
  {
    children,
    style,
    flex,
    flexShrink,
    flexWrap,
    row,
    col,
    absolute,
    position,
    justify,
    align,
    self,
    width,
    height,
    maxWidth,
    minWidth,
    maxHeight,
    minHeight,
    square,
    round,
    m,
    mx,
    my,
    mt,
    mb,
    ml,
    mr,
    p,
    px,
    py,
    pt,
    pb,
    pl,
    pr,
    gap,
    color,
    radius,
    radiusTop,
    radiusBottom,
    border,
    borderColor,
    overflow,
    opacity,
    top,
    bottom,
    left,
    right,
    ...viewProps
  },
  ref,
) {
  const computedStyle = buildStyle({
    flex,
    flexShrink,
    flexWrap,
    row,
    col,
    absolute,
    position,
    justify,
    align,
    self,
    width,
    height,
    maxWidth,
    minWidth,
    maxHeight,
    minHeight,
    square,
    round,
    m,
    mx,
    my,
    mt,
    mb,
    ml,
    mr,
    p,
    px,
    py,
    pt,
    pb,
    pl,
    pr,
    gap,
    color,
    radius,
    radiusTop,
    radiusBottom,
    border,
    borderColor,
    overflow,
    opacity,
    top,
    bottom,
    left,
    right,
  });

  return (
    <NativeView ref={ref} style={[computedStyle, style]} {...viewProps}>
      {children}
    </NativeView>
  );
});
